# Identificación del proyecto (de SonarCloud)
sonar.projectKey=miggonort1_PGPIPAAS
sonar.organization=miggonort1
sonar.projectVersion=1.0

# Configuración específica para Django/Python
sonar.sources=./proyecto
sonar.python.coverage.reportPaths=./coverage.xml
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**
sonar.sourceEncoding=UTF-8

# Calidad del código (Python)
sonar.python.pylint.reportPaths=./pylint_report.txt
sonar.python.bandit.reportPaths=./bandit_report.json

# Quality Gate (bloquear si hay fallos críticos)
sonar.qualitygate.wait=true
