# Generated by Django 5.1.3 on 2024-11-24 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('duracion_semanas', models.IntegerField()),
                ('plazas_disponibles', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(default='/static/images/bomberos.jpg', max_length=200)),
                ('departamento', models.CharField(choices=[('MD', 'Madrid'), ('BCN', 'Barcelona'), ('VAL', 'Valencia'), ('SEV', 'Sevilla'), ('ZGZ', 'Zaragoza'), ('MAL', 'Málaga'), ('BIL', 'Bilbao'), ('VLL', 'Valladolid')], default='MD', max_length=3)),
                ('sector_laboral', models.CharField(choices=[('ADM', 'Administración Pública'), ('JUS', 'Justicia'), ('SAL', 'Sanidad'), ('EDU', 'Educación'), ('POL', 'Policía Nacional'), ('GUA', 'Guardia Civil'), ('BOM', 'Bomberos'), ('FIS', 'Fiscalía'), ('PRI', 'Prisiones'), ('TRA', 'Tráfico')], default='ADM', max_length=3)),
                ('fabricante', models.CharField(choices=[('OP', 'OpositaConmigo'), ('EDX', 'edX'), ('US', 'Universidad de Sevilla'), ('BU', 'Bomberos Unidos'), ('JCE', 'Justicia Con Experiencia')], default='OP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='ID de Sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(blank=True, choices=[('PEN', 'Pendiente de pago'), ('PAG', 'Pagado'), ('ENV', 'Enviado'), ('ENT', 'Entregado')], default='PEN', max_length=3, null=True, verbose_name='Estado del Pedido')),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Envío')),
                ('ciudad_envio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Envío')),
                ('provincia_envio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia de Envío')),
                ('codigo_postal_envio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal de Envío')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total del Pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_pedidos', to='cursos.curso')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.carrito')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='cursos.curso')),
            ],
            options={
                'unique_together': {('carrito', 'curso')},
            },
        ),
    ]
