# Generated by Django 5.1.3 on 2024-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.CharField(default='/static/images/bomberos.jpg', max_length=200),
        ),
    ]
