# Generated by Django 5.1.3 on 2024-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocurso',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
