# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAadircursoalcarrito():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aadircursoalcarrito(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.CSS_SELECTOR, "#soon-courses .course-card:nth-child(1) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    self.driver.find_element(By.ID, "cart-button").click()
  
