# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestOrdenacionpaginainicio:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()  # Asegura que la ventana está maximizada
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_ordenacionpaginainicio(self):
        self.driver.get("http://127.0.0.1:8000/")
        
        # Interacciones con la página
        self.seleccionar_opcion(By.ID, "orden", "Fecha de inicio")
        self.seleccionar_opcion(By.ID, "orden", "Precio")
        self.seleccionar_opcion(By.ID, "orden", "Plazas disponibles")
        self.seleccionar_opcion(By.ID, "direccion", "Descendente")
        self.seleccionar_opcion(By.ID, "orden", "Precio")
        self.seleccionar_opcion(By.ID, "orden", "Fecha de inicio")

    def seleccionar_opcion(self, by_locator, element_id, opcion_texto):
        # Desplazar el elemento al centro de la vista
        dropdown = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((by_locator, element_id))
        )
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", dropdown)

        # Verificar que el elemento sea clickeable
        dropdown = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((by_locator, element_id))
        )
        dropdown.click()
        
        # Seleccionar la opción del desplegable
        opcion = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.XPATH, f"//select[@id='{element_id}']//option[. = '{opcion_texto}']"))
        )
        opcion.click()

