services:
  - type: web
    name: web-service
    env: docker
    plan: starter  # Cambia según tus necesidades
    dockerfilePath: Dockerfile  # Usa el Dockerfile de tu aplicación
    buildCommand: ""  # Render construirá la imagen automáticamente
    startCommand: >
      sh -c "wait-for-it db:3306 -- python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: ENVIRONMENT
        value: "docker"
      - key: DB_HOST
        value: "db"
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "dbpgpipaas"
      - key: DB_USER
        value: "pgpipaas_user"
      - key: DB_PASSWORD
        value: "pgpipaas_password"
      - key: SECRET_KEY
        value: "<tu-clave-secreta>"
      - key: DEBUG
        value: "True"  # Cambia a False en producción
      - key: ALLOWED_HOSTS
        value: "*"
    ports:
      - 8000
    dependsOn:
      - name: db-service

  - type: private_service
    name: db-service
    env: docker
    dockerfilePath: ""  # No necesita un Dockerfile porque usamos una imagen pública
    image: mariadb:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: "rootpassword"
      - key: MYSQL_DATABASE
        value: "dbpgpipaas"
      - key: MYSQL_USER
        value: "pgpipaas_user"
      - key: MYSQL_PASSWORD
        value: "pgpipaas_password"
