# Identificación del proyecto (de SonarCloud)
sonar.projectKey=miggonort1_PGPIPAAS
sonar.organization=miggonort1

# Configuración específica para Django/Python
sonar.python.coverage.reportPaths=./coverage.xml
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**
sonar.sourceEncoding=UTF-8

