name: DevSecOps Pipeline

on:
  push:
    branches: [ develop, devsecops-pipeline ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r proyecto/requirements.txt      

    - name: Run Trivy (IaC scanning with report output)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: './proyecto'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy report to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
