name: Trivy Security Scan

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Trivy IaC scan (diff)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          config-policy: 'terraform,kubernetes' # Ajusta según tus tipos de IaC
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exclude: '**/tests/**,**/examples/**' # Ajusta tus exclusiones
          diff-from: ${{ github.event.pull_request.base.sha }}

      - name: Upload Trivy report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          wait-for-processing: true
